### PR TITLE
Add option to skip signing the unified efi image

### PR DESCRIPTION
**Pull request by osimarr**
sbupdate is not only a helper to sign the efi image, but also to
manage and compose the unified kernel image. Systems that doesn't
support secure boot can still benefit from it.
This patch adds a config option to skip efi signature.

Signed-off-by: David Cohen <dacohen@pm.me>

### CODE REVIEW

**Comment by Maryse47** [comment]
Out of curiosity: what are the benefits of unified kernel image without signature? Possibility of /boot encryption?

**Comment by osimarr** [comment]
> Out of curiosity: what are the benefits of unified kernel image without signature? Possibility of /boot encryption?

Boot encryption is my main reason. I use systemd-boot and don't need to create the extra efi/boot partition.

**Comment by andreyv** [comment]
Hi,

Image signing is the main task of `sbupdate`, so I think this feature is out of scope.

If you want to boot the kernel as an UEFI executable, you can use [EFISTUB](https://wiki.archlinux.org/title/EFISTUB).

**Comment by andreyv** [comment]
Use `mkinitcpio --uefi` to create UEFI images without signing.

**Pull request closed without merging**
