### PR TITLE
Remove unnecessary wait

### PR DESCRIPTION
**Pull request by brandsimon**

### CODE REVIEW

**Comment by andreyv** [comment]
The `wait` is necessary to check the exit status of the `<(cat "${INITRD_PREPEND[@]}" "${initrd}")` process substitution. Otherwise it could fail and the script would continue nonetheless.

See c0a7e52aa5ce4dcb1c2de2cf59e66728654a940d.

**Comment by brandsimon** [comment]
I checked the manpage, and `wait` waits for process completion, there is no exit status check.
What am I missing?

**Comment by andreyv** [comment]
See the last sentence in the description of `wait` in the `bash(1)` man page:
> Otherwise, the return status is the exit status of the last process or job waited for.

**Comment by brandsimon** [comment]
Ah, now I see, I did not know the `set -e` was set.
Thank you.

**Pull request closed without merging**
