### PR TITLE
Build efi file for additional initrds

### PR DESCRIPTION
**Pull request by brandsimon**
As discussed in #11, here is the PR.
 If this is not the preferred solution (especially the config file, I dont know a better way in bash), I am happy to adapt the PR.

### CODE REVIEW

**Comment by andreyv** [comment]
Thanks, looks about right :)

I'll check this in a few days. One note: you should convert the `INITRD[<NAME>]` variable to a Bash array, like this:
```
INITRD[linux]=('.../initrd1' '.../initrd2')
```
This makes handling easier and more robust. See other array variables for examples.

You can also run `shellcheck` on the script.

**Comment by brandsimon** [comment]
@andreyv Yes, thats what I tried first, but as I found out, bash does not support 2-dimensional arrays:
```
$ declare -A YYY
$ YYY['test']=()
bash: YYY['test']: cannot assign list to array member
```
`shellcheck` is a good advice, thanks. I used it before, but I am rarely scripting in bash, so I forgot it. Passed :)

**Comment by andreyv** [comment]
Thanks, I didn't know that. Then the "correct" solution would be to change `INITRD[linux]` to `INITRD_linux`, but as this affects also `CMDLINE[<NAME>]`, then it is out of scope for this PR.

I pushed these changes with small modifications as 479eb88175ca8683eb251492b6d1ecf9e9a392d7 on master. Could you please verify that they work as expected?

**Comment by brandsimon** [comment]
@andreyv Great, thank you :)
They work for me. 
I tested:
- Removing kernel
- Installing kernel
- Reinstalling (updating) kernel
- Running script directly

Is there anything missing?

If we change the variable to INITRD_linux we are not backwards-compatible anymore, but I agree, the current solution is not optimal.

**Comment by andreyv** [comment]
Thanks, that's more than enough. I'll close this PR then.

**Pull request closed without merging**
